---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set default incoming policy to deny
  ufw:
    direction: incoming
    policy: deny

- name: Set default outgoing policy to allow
  ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH (port 22)
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS (port 443)
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
