---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: safe

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - apt-transport-https
      - ca-certificates
      - gnupg
      - python3-pip
      - lsb-release
    state: present
